node_js:
  - "6"
env:
  - TEST_SASS_VERSION="~> 3.0"
  - TEST_SASS_VERSION="~> 3.4"
  - TEST_SASS_VERSION="~> 3.3"
  - TEST_SASS_VERSION="~> 3.2"
  - NODE_SASS_VERSION=latest
  - NODE_SASS_VERSION="3.7.x"
  - NODE_SASS_VERSION="3.6.x"
  - NODE_SASS_VERSION="3.5.x"
  - NODE_SASS_VERSION="3.4.x"
before_install:
  - travis/install.sh
script:
  - travis/test.sh
